apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
  namespace: node-app
  annotations:
    fluxcd.io/automated: "true"
spec:
  selector:
    matchLabels:
      app: node-app-deployment
  template:
    metadata:
      labels:
        app: node-app-deployment
    spec:
      containers:
        - name: node-app-image
          image: omslinx.azurecr.io/oms/node-web-app:latest
          resources:
            limits:
              memory: "256Mi"
              cpu: "200m"
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /var/www/html
              name: node-app-pvc
      restartPolicy: Always
      volumes:
        - name: node-app-pvc
          persistentVolumeClaim:
            claimName: node-app-pvc
