---
apiVersion: v1
kind: Service
metadata:
  name: node-service
  namespace: node-app
spec:
  type: LoadBalancer
  selector:
    app: node-app-deployment
  ports:
     - protocol: TCP
       port: 80
