on: [push]
name: Linux_Container_Workflow

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@main

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: ${{ secrets.CLUSTER_NAME }}
        resource-group: ${{ secrets.RESOURCE_GROUP }}
    
    - name: 'Build and push image'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/oms/node-web-app:${{ github.sha }}
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/oms/node-web-app:${{ github.sha }}

    - name: 'Deploy'    
    - uses: Azure/k8s-deploy@v1.4
      with:
        namespace: 'node-app'
        manifests: |
            kubernetes/node-deployment.yaml
            kubernetes/services.yaml
        images: 'omslinx.azurecr.io/oms/node-web-app:${{ github.sha }}'
